// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt3BN2NPuG4nx-buv2sH_h3MvJFQY-wpc',
    appId: '1:183894934184:web:c6b05be40fd358a309389d',
    messagingSenderId: '183894934184',
    projectId: 'servicos-itinerantes',
    authDomain: 'servicos-itinerantes.firebaseapp.com',
    databaseURL: 'https://servicos-itinerantes-default-rtdb.firebaseio.com',
    storageBucket: 'servicos-itinerantes.appspot.com',
    measurementId: 'G-RHTDTP732T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKDxpslCjSnHU2puTEY6Ct6sXMR4LvJ_k',
    appId: '1:183894934184:android:5468017a1b04833d09389d',
    messagingSenderId: '183894934184',
    projectId: 'servicos-itinerantes',
    databaseURL: 'https://servicos-itinerantes-default-rtdb.firebaseio.com',
    storageBucket: 'servicos-itinerantes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMYANH-8QCin2sRGMTTmryhufMajxTiU',
    appId: '1:183894934184:ios:235822519d19e9f509389d',
    messagingSenderId: '183894934184',
    projectId: 'servicos-itinerantes',
    databaseURL: 'https://servicos-itinerantes-default-rtdb.firebaseio.com',
    storageBucket: 'servicos-itinerantes.appspot.com',
    iosClientId: '183894934184-gi4tjjgrnq1oq6ug0h5nj26dsq03bvp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProjetoItinerante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwMYANH-8QCin2sRGMTTmryhufMajxTiU',
    appId: '1:183894934184:ios:5612050dd7fc845309389d',
    messagingSenderId: '183894934184',
    projectId: 'servicos-itinerantes',
    databaseURL: 'https://servicos-itinerantes-default-rtdb.firebaseio.com',
    storageBucket: 'servicos-itinerantes.appspot.com',
    iosClientId: '183894934184-169hp38scecfq2vs4hu3evbde6mdkj11.apps.googleusercontent.com',
    iosBundleId: 'com.example.appprojetoitinerante',
  );
}
